script:
  - touch a
  # Test if the key is leaking.
  - env
after_success: |
  mkdir gh-pages
  cd gh-pages
  git init
  git checkout -b gh-pages
  echo hello > index.html
  git add .
  git commit -m init
  GIT_AUTHOR_NAME="travis" GIT_AUTHOR_EMAIL="travis" git push -f https://cirosantilli:$GITHUB_API_KEY_ENCRYPTED@github.com/cirosantilli/test-travis-push gh-pages
deploy:
  provider: releases
  api_key:
    secure: "p4W/g9w0FVA6Cy1pkHkTsW1rNDZj8DqBHL2XQHr9CHu8zcL8Ns0cNvNPNDPAlRq6NeZ6S6Bdu4wBdhYtwScHZ+uolyvsJeRB+J4u7DKyr2R8v1XdojkSo5mgVPLF/1WShVDuzhnJjJk+FKckp5MlrJQtcZRBD5OAmxniacpsjv4FimYcsZouedTzEJ6Gyqt1C5J/xM0SU5uPx54QAjsOOg4PWGftg/sTEQhOj5bmQUCOx/fqOtGw9XVCeRKqqORIv2Q3l3nO041H05/wj5HRCXzxf+c2xG+TZK6qqBLBsNbYIwQBs3Iw/lwo7Ky+GbdxVNViqsl2VUp9uU4zczGnFmXd+S95M4SxJkUCGa6XcF7YoS5y0tGGxZ6hzN/y/8oUK5GDpaNW4rnhlXBWrlvumYZocWomCliWzM3AmLXarJhggX2tnfMPkGcLRwB4RTS4lmutRUjaZ4aCAdvMc3NKGqMFPF5RTKWfiAjn+B1H29cFung/8ijyC9LjV0OxApGoC+u666LQw6xSE2Ij62lOgBRbfViJryE6vxp537+PpD6KnpOwuyaEEbOXm7jcwX/vfU/R6BeyHnFd2lHLGKZEVvwbv0C+Z0epAtTmscrbVE+amT9s6iv5iq5hs4CjZgeBoa7XdSN9BPyTVRa1LbPiCfCf6VuD1iDB60F1FMdJgoA="
  file: a
  skip_cleanup: true
  on:
    tags: true
env:
  - secure: "evSswc9QV8NPI5wzv2Uv+hvMKdqXdF/ZIDbZMyGGkocEvQtPqa5R7uQtAXFibzqBJ5E7p24jcTuHzXI87sPpvcDBao4s5dq+ErkOOh4MWJ7DNneF+GStSWxXMHqBik8AgQy3lw9P1lzgb+vv5BXthfedOIso9H464rNtPmMUYvmsxImN76YugRW29raibXL1fji6PVD5Ia+AVyOhcr1a2Qal44jtATgqVMlgOlXawaE720qnyd5Gh2zdR7xfEE6nbXL8hriJpoH4MyF0YYqtmFs7x9vuzbctGdjuFx6t0Nml25N+xNDIJ8NA+TgimtPwKgma6h+yYkvB4Px+oJ30HlqL3JGS8MsNk26MdaEizp7pwf+LzrwqzUrAaBrHEsPTrXPkgYpnshTVsotmZm0OURdoBfZU4nex0n+ubT5Y6N3dTzEYvEn3Qy6WGszaCR4zlUi5f5CMndQfxoxALvtzf+dckZcMbhh6T1fCmYyqgo2xCVnJ7igSzuiR1rgy5DgW/T+E6M4veezDKHTkkcZFSeK/xr/htKMmJ+Hw/k0HjFTtY4m2/5e2eb4odNn5zWhkP/kbFJ0N+rj5bk3HnUPUohg71yFmzW4L7knFlyVJo9bPQAbExc30fcDF+Im+WUlWptWNrCUJviG3bi8I7VqFmyaQv1NqBxmw4WL2xLDHXWo="
